#!/usr/bin/env bash
# bash script for FizzBuzz

for n in {1..100}
do
	if [ $((n%15)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n%5)) == 0 ]
        then
                echo "Buzz"
	elif [ $((n%3)) == 0 ]
        then
                echo "Fizz"
	else
		echo "$n"
	fi
done
